// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Changed(arg1:main.World):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Load():Promise<main.World>;

export function Save(arg1:main.World,arg2:boolean):Promise<void>;
