// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Changed(arg1) {
  return window['go']['main']['App']['Changed'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Load() {
  return window['go']['main']['App']['Load']();
}

export function Save(arg1, arg2) {
  return window['go']['main']['App']['Save'](arg1, arg2);
}
